Repository analog-m4/analog_fe, pull requests merged in 2023-12, with the labels that each got.

#29 6 Render a project board with columns and tasks
  src/components/Account/Account.js
  src/components/App/App.js
  src/components/Column/Column.js
  src/components/Dashboard/Dashboard.js
  src/components/Header/Header.js
  src/components/Project/Project.js
  src/components/ProjectBoard/ProjectBoard.js
  src/components/Task/Task.js
  src/components/Welcome/Welcome.js
Labels: front-end

#30 7 Update UI
  public/index.html
  src/components/Account/Account.js
  src/components/App/App.js
  src/components/Column/Column.js
  src/components/Dashboard/Dashboard.js
  src/components/Header/Header.js
  src/components/Project/Project.js
  src/components/ProjectBoard/ProjectBoard.js
  src/components/Task/Task.js
  src/images/sample-avatar.png
  src/index.css
  tailwind.config.js
Labels: front-end, ui

#43 39 Implement bootstrap for add project and add task modal
  src/AddProject/AddProject.js
  src/components/AddTask/AddTask.js
  src/components/Dashboard/Dashboard.js
  src/components/EditTask/EditTask.js
  src/components/FileUpload/FileUpload.js
  src/components/Project/Project.js
  src/components/ProjectBoard/ProjectBoard.js
Labels: front-end

#44 Connect the front end and backend
  src/AddProject/AddProject.js
  src/apiCalls.js
  src/components/AddTask/AddTask.js
  src/components/App/App.js
  src/components/Column/Column.js
  src/components/Dashboard/Dashboard.js
  src/components/EditTask/EditTask.js
  src/components/ProjectBoard/ProjectBoard.js
  src/reducers/user.js
Labels: front-end

#52 18, 37, 38 Implement POST, PATCH
  src/apiCalls.js
  src/components/AddProject/AddProject.js
  src/components/AddTask/AddTask.js
  src/components/App/App.js
  src/components/Dashboard/Dashboard.js
  src/components/EditTask/EditTask.js
  src/components/FileUpload/FileUpload.js
  src/components/ProjectBoard/ProjectBoard.js
  src/components/WhiteBoard/WhiteBoard.js
  src/reducers/user.js
Labels: front-end

#64 53 Update UI
  package-lock.json
  package.json
  src/components/About/About.js
  src/components/Account/Account.js
  src/components/AddProject/AddProject.js
  src/components/AddTask/AddTask.js
  src/components/BasicModal/BasicModal.js
  src/components/BuiltWith/BuiltWith.js
  src/components/Column/Column.js
  src/components/Dashboard/Dashboard.js
  src/components/EditTask/EditTask.js
  src/components/FileUpload/FileUpload.js
  src/components/Header/Header.js
  src/components/Login/Login.js
  src/components/Project/Project.js
  src/components/ProjectBoard/ProjectBoard.js
  src/components/Task/Task.js
  src/components/Welcome/Welcome.js
  src/components/WhiteBoard/WhiteBoard.js
  src/images/sample-avatar.png
  src/index.css
  tailwind.config.js
Labels: enhancement, front-end

#74 61 Code cleanup
  src/apiCalls.js
  src/components/About/About.js
  src/components/Account/Account.js
  src/components/AddProject/AddProject.js
  src/components/AddTask/AddTask.js
  src/components/App/App.js
  src/components/BuiltWith/BuiltWith.js
  src/components/Column/Column.js
  src/components/Dashboard/Dashboard.js
  src/components/EditTask/EditTask.js
  src/components/FileUpload/FileUpload.js
  src/components/Login/Login.js
  src/components/Project/Project.js
  src/components/ProjectBoard/ProjectBoard.js
  src/components/Task/Task.js
  src/components/Welcome/Welcome.js
  src/components/WhiteBoard/WhiteBoard.js
  src/reducers/user.js
Labels: front-end
